# PostgreSQL. Versions 9.1 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  username: 'postgres'
  password: 'postgres'

development:
  <<: *default
  database: coin_cobbler_development
production:
  <<: *default
  database: coin_cobbler_production
