# PostgreSQL. Versions 9.1 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'

development:
  <<: *default
  database: flutter_development
